/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrowseFilter {
  'minPriceKES' : [] | [bigint],
  'sortOrder' : SortOrder,
  'maxPriceKES' : [] | [bigint],
  'category' : [] | [Category],
  'keyword' : [] | [string],
}
export type Campus = string;
export type Category = { 'HouseItems' : null } |
  { 'Clothes' : null } |
  { 'Books' : null } |
  { 'Electronics' : null } |
  { 'BedsAndMattresses' : null };
export interface CreateItemInput {
  'title' : string,
  'imageRefs' : Array<string>,
  'description' : string,
  'category' : Category,
  'priceKES' : bigint,
}
export type ItemId = bigint;
export type ItemStatus = { 'active' : null } |
  { 'sold' : null };
export interface ItemView {
  'id' : ItemId,
  'status' : ItemStatus,
  'title' : string,
  'sellerWhatsapp' : string,
  'imageRefs' : Array<string>,
  'createdAt' : Timestamp,
  'description' : string,
  'seller' : UserId,
  'updatedAt' : Timestamp,
  'category' : Category,
  'priceKES' : bigint,
}
export interface PageResult {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<ItemView>,
}
export interface ProfileView {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'campus' : Campus,
  'registrationMethod' : RegistrationMethod,
  'whatsappPhone' : string,
}
export interface RegisterInput {
  'name' : string,
  'campus' : Campus,
  'registrationMethod' : RegistrationMethod,
  'whatsappPhone' : string,
}
export type RegistrationMethod = { 'email' : string } |
  { 'phone' : string };
export type SortOrder = { 'newest' : null } |
  { 'priceDesc' : null } |
  { 'priceAsc' : null };
export type Timestamp = bigint;
export interface UpdateItemInput {
  'title' : string,
  'imageRefs' : Array<string>,
  'description' : string,
  'category' : Category,
  'priceKES' : bigint,
}
export interface UpdateProfileInput {
  'name' : string,
  'whatsappPhone' : string,
}
export type UserId = Principal;
export interface _SERVICE {
  'browseItems' : ActorMethod<[BrowseFilter, bigint, bigint], PageResult>,
  'createItem' : ActorMethod<
    [CreateItemInput],
    { 'ok' : ItemView } |
      { 'err' : string }
  >,
  'deleteItem' : ActorMethod<
    [ItemId],
    { 'ok' : null } |
      { 'notFound' : null } |
      { 'unauthorized' : null }
  >,
  'getItem' : ActorMethod<[ItemId], [] | [ItemView]>,
  'getMyListings' : ActorMethod<[], Array<ItemView>>,
  'getMyProfile' : ActorMethod<[], [] | [ProfileView]>,
  'getProfile' : ActorMethod<[UserId], [] | [ProfileView]>,
  'markSold' : ActorMethod<
    [ItemId],
    { 'ok' : null } |
      { 'notFound' : null } |
      { 'unauthorized' : null }
  >,
  'register' : ActorMethod<
    [RegisterInput],
    { 'ok' : ProfileView } |
      { 'err' : string }
  >,
  'updateItem' : ActorMethod<
    [ItemId, UpdateItemInput],
    { 'ok' : null } |
      { 'notFound' : null } |
      { 'unauthorized' : null }
  >,
  'updateProfile' : ActorMethod<
    [UpdateProfileInput],
    { 'ok' : ProfileView } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];