/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SortOrder = IDL.Variant({
  'newest' : IDL.Null,
  'priceDesc' : IDL.Null,
  'priceAsc' : IDL.Null,
});
export const Category = IDL.Variant({
  'HouseItems' : IDL.Null,
  'Clothes' : IDL.Null,
  'Books' : IDL.Null,
  'Electronics' : IDL.Null,
  'BedsAndMattresses' : IDL.Null,
});
export const BrowseFilter = IDL.Record({
  'minPriceKES' : IDL.Opt(IDL.Nat),
  'sortOrder' : SortOrder,
  'maxPriceKES' : IDL.Opt(IDL.Nat),
  'category' : IDL.Opt(Category),
  'keyword' : IDL.Opt(IDL.Text),
});
export const ItemId = IDL.Nat;
export const ItemStatus = IDL.Variant({
  'active' : IDL.Null,
  'sold' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const ItemView = IDL.Record({
  'id' : ItemId,
  'status' : ItemStatus,
  'title' : IDL.Text,
  'sellerWhatsapp' : IDL.Text,
  'imageRefs' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'seller' : UserId,
  'updatedAt' : Timestamp,
  'category' : Category,
  'priceKES' : IDL.Nat,
});
export const PageResult = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(ItemView),
});
export const CreateItemInput = IDL.Record({
  'title' : IDL.Text,
  'imageRefs' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : Category,
  'priceKES' : IDL.Nat,
});
export const Campus = IDL.Text;
export const RegistrationMethod = IDL.Variant({
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProfileView = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'campus' : Campus,
  'registrationMethod' : RegistrationMethod,
  'whatsappPhone' : IDL.Text,
});
export const RegisterInput = IDL.Record({
  'name' : IDL.Text,
  'campus' : Campus,
  'registrationMethod' : RegistrationMethod,
  'whatsappPhone' : IDL.Text,
});
export const UpdateItemInput = IDL.Record({
  'title' : IDL.Text,
  'imageRefs' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : Category,
  'priceKES' : IDL.Nat,
});
export const UpdateProfileInput = IDL.Record({
  'name' : IDL.Text,
  'whatsappPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  'browseItems' : IDL.Func(
      [BrowseFilter, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'createItem' : IDL.Func(
      [CreateItemInput],
      [IDL.Variant({ 'ok' : ItemView, 'err' : IDL.Text })],
      [],
    ),
  'deleteItem' : IDL.Func(
      [ItemId],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'notFound' : IDL.Null,
          'unauthorized' : IDL.Null,
        }),
      ],
      [],
    ),
  'getItem' : IDL.Func([ItemId], [IDL.Opt(ItemView)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(ItemView)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(ProfileView)], ['query']),
  'markSold' : IDL.Func(
      [ItemId],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'notFound' : IDL.Null,
          'unauthorized' : IDL.Null,
        }),
      ],
      [],
    ),
  'register' : IDL.Func(
      [RegisterInput],
      [IDL.Variant({ 'ok' : ProfileView, 'err' : IDL.Text })],
      [],
    ),
  'updateItem' : IDL.Func(
      [ItemId, UpdateItemInput],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'notFound' : IDL.Null,
          'unauthorized' : IDL.Null,
        }),
      ],
      [],
    ),
  'updateProfile' : IDL.Func(
      [UpdateProfileInput],
      [IDL.Variant({ 'ok' : ProfileView, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SortOrder = IDL.Variant({
    'newest' : IDL.Null,
    'priceDesc' : IDL.Null,
    'priceAsc' : IDL.Null,
  });
  const Category = IDL.Variant({
    'HouseItems' : IDL.Null,
    'Clothes' : IDL.Null,
    'Books' : IDL.Null,
    'Electronics' : IDL.Null,
    'BedsAndMattresses' : IDL.Null,
  });
  const BrowseFilter = IDL.Record({
    'minPriceKES' : IDL.Opt(IDL.Nat),
    'sortOrder' : SortOrder,
    'maxPriceKES' : IDL.Opt(IDL.Nat),
    'category' : IDL.Opt(Category),
    'keyword' : IDL.Opt(IDL.Text),
  });
  const ItemId = IDL.Nat;
  const ItemStatus = IDL.Variant({ 'active' : IDL.Null, 'sold' : IDL.Null });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const ItemView = IDL.Record({
    'id' : ItemId,
    'status' : ItemStatus,
    'title' : IDL.Text,
    'sellerWhatsapp' : IDL.Text,
    'imageRefs' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'seller' : UserId,
    'updatedAt' : Timestamp,
    'category' : Category,
    'priceKES' : IDL.Nat,
  });
  const PageResult = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(ItemView),
  });
  const CreateItemInput = IDL.Record({
    'title' : IDL.Text,
    'imageRefs' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : Category,
    'priceKES' : IDL.Nat,
  });
  const Campus = IDL.Text;
  const RegistrationMethod = IDL.Variant({
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProfileView = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'campus' : Campus,
    'registrationMethod' : RegistrationMethod,
    'whatsappPhone' : IDL.Text,
  });
  const RegisterInput = IDL.Record({
    'name' : IDL.Text,
    'campus' : Campus,
    'registrationMethod' : RegistrationMethod,
    'whatsappPhone' : IDL.Text,
  });
  const UpdateItemInput = IDL.Record({
    'title' : IDL.Text,
    'imageRefs' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : Category,
    'priceKES' : IDL.Nat,
  });
  const UpdateProfileInput = IDL.Record({
    'name' : IDL.Text,
    'whatsappPhone' : IDL.Text,
  });
  
  return IDL.Service({
    'browseItems' : IDL.Func(
        [BrowseFilter, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'createItem' : IDL.Func(
        [CreateItemInput],
        [IDL.Variant({ 'ok' : ItemView, 'err' : IDL.Text })],
        [],
      ),
    'deleteItem' : IDL.Func(
        [ItemId],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'notFound' : IDL.Null,
            'unauthorized' : IDL.Null,
          }),
        ],
        [],
      ),
    'getItem' : IDL.Func([ItemId], [IDL.Opt(ItemView)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(ItemView)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(ProfileView)], ['query']),
    'markSold' : IDL.Func(
        [ItemId],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'notFound' : IDL.Null,
            'unauthorized' : IDL.Null,
          }),
        ],
        [],
      ),
    'register' : IDL.Func(
        [RegisterInput],
        [IDL.Variant({ 'ok' : ProfileView, 'err' : IDL.Text })],
        [],
      ),
    'updateItem' : IDL.Func(
        [ItemId, UpdateItemInput],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'notFound' : IDL.Null,
            'unauthorized' : IDL.Null,
          }),
        ],
        [],
      ),
    'updateProfile' : IDL.Func(
        [UpdateProfileInput],
        [IDL.Variant({ 'ok' : ProfileView, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };