/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface UpdateItemInput {
    title: string;
    imageRefs: Array<string>;
    description: string;
    category: Category;
    priceKES: bigint;
}
export interface CreateItemInput {
    title: string;
    imageRefs: Array<string>;
    description: string;
    category: Category;
    priceKES: bigint;
}
export type RegistrationMethod = {
    __kind__: "email";
    email: string;
} | {
    __kind__: "phone";
    phone: string;
};
export interface ProfileView {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    campus: Campus;
    registrationMethod: RegistrationMethod;
    whatsappPhone: string;
}
export type UserId = Principal;
export interface UpdateProfileInput {
    name: string;
    whatsappPhone: string;
}
export type ItemId = bigint;
export interface RegisterInput {
    name: string;
    campus: Campus;
    registrationMethod: RegistrationMethod;
    whatsappPhone: string;
}
export interface ItemView {
    id: ItemId;
    status: ItemStatus;
    title: string;
    sellerWhatsapp: string;
    imageRefs: Array<string>;
    createdAt: Timestamp;
    description: string;
    seller: UserId;
    updatedAt: Timestamp;
    category: Category;
    priceKES: bigint;
}
export interface BrowseFilter {
    minPriceKES?: bigint;
    sortOrder: SortOrder;
    maxPriceKES?: bigint;
    category?: Category;
    keyword?: string;
}
export interface PageResult {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<ItemView>;
}
export type Campus = string;
export enum Category {
    HouseItems = "HouseItems",
    Clothes = "Clothes",
    Books = "Books",
    Electronics = "Electronics",
    BedsAndMattresses = "BedsAndMattresses"
}
export enum ItemStatus {
    active = "active",
    sold = "sold"
}
export enum SortOrder {
    newest = "newest",
    priceDesc = "priceDesc",
    priceAsc = "priceAsc"
}
export enum Variant_ok_notFound_unauthorized {
    ok = "ok",
    notFound = "notFound",
    unauthorized = "unauthorized"
}
export interface backendInterface {
    browseItems(filter: BrowseFilter, offset: bigint, limit: bigint): Promise<PageResult>;
    createItem(input: CreateItemInput): Promise<{
        __kind__: "ok";
        ok: ItemView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteItem(itemId: ItemId): Promise<Variant_ok_notFound_unauthorized>;
    getItem(itemId: ItemId): Promise<ItemView | null>;
    getMyListings(): Promise<Array<ItemView>>;
    getMyProfile(): Promise<ProfileView | null>;
    getProfile(userId: UserId): Promise<ProfileView | null>;
    markSold(itemId: ItemId): Promise<Variant_ok_notFound_unauthorized>;
    register(input: RegisterInput): Promise<{
        __kind__: "ok";
        ok: ProfileView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateItem(itemId: ItemId, input: UpdateItemInput): Promise<Variant_ok_notFound_unauthorized>;
    updateProfile(input: UpdateProfileInput): Promise<{
        __kind__: "ok";
        ok: ProfileView;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { BrowseFilter as _BrowseFilter, Campus as _Campus, Category as _Category, CreateItemInput as _CreateItemInput, ItemId as _ItemId, ItemStatus as _ItemStatus, ItemView as _ItemView, PageResult as _PageResult, ProfileView as _ProfileView, RegisterInput as _RegisterInput, RegistrationMethod as _RegistrationMethod, SortOrder as _SortOrder, Timestamp as _Timestamp, UpdateItemInput as _UpdateItemInput, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async browseItems(arg0: BrowseFilter, arg1: bigint, arg2: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.browseItems(to_candid_BrowseFilter_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PageResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseItems(to_candid_BrowseFilter_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PageResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createItem(arg0: CreateItemInput): Promise<{
        __kind__: "ok";
        ok: ItemView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createItem(to_candid_CreateItemInput_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItem(to_candid_CreateItemInput_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteItem(arg0: ItemId): Promise<Variant_ok_notFound_unauthorized> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItem(arg0: ItemId): Promise<ItemView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyListings(): Promise<Array<ItemView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<ProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<ProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async markSold(arg0: ItemId): Promise<Variant_ok_notFound_unauthorized> {
        if (this.processError) {
            try {
                const result = await this.actor.markSold(arg0);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSold(arg0);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: RegisterInput): Promise<{
        __kind__: "ok";
        ok: ProfileView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.register(to_candid_RegisterInput_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(to_candid_RegisterInput_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateItem(arg0: ItemId, arg1: UpdateItemInput): Promise<Variant_ok_notFound_unauthorized> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, to_candid_UpdateItemInput_n31(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, to_candid_UpdateItemInput_n31(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: UpdateProfileInput): Promise<{
        __kind__: "ok";
        ok: ProfileView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ItemStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemStatus): ItemStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ItemView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemView): ItemView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PageResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageResult): PageResult {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileView_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileView): ProfileView {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationMethod_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationMethod): RegistrationMethod {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ItemView]): ItemView | null {
    return value.length === 0 ? null : from_candid_ItemView_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileView]): ProfileView | null {
    return value.length === 0 ? null : from_candid_ProfileView_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    status: _ItemStatus;
    title: string;
    sellerWhatsapp: string;
    imageRefs: Array<string>;
    createdAt: _Timestamp;
    description: string;
    seller: _UserId;
    updatedAt: _Timestamp;
    category: _Category;
    priceKES: bigint;
}): {
    id: ItemId;
    status: ItemStatus;
    title: string;
    sellerWhatsapp: string;
    imageRefs: Array<string>;
    createdAt: Timestamp;
    description: string;
    seller: UserId;
    updatedAt: Timestamp;
    category: Category;
    priceKES: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ItemStatus_n12(_uploadFile, _downloadFile, value.status),
        title: value.title,
        sellerWhatsapp: value.sellerWhatsapp,
        imageRefs: value.imageRefs,
        createdAt: value.createdAt,
        description: value.description,
        seller: value.seller,
        updatedAt: value.updatedAt,
        category: from_candid_Category_n14(_uploadFile, _downloadFile, value.category),
        priceKES: value.priceKES
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    campus: _Campus;
    registrationMethod: _RegistrationMethod;
    whatsappPhone: string;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    campus: Campus;
    registrationMethod: RegistrationMethod;
    whatsappPhone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        campus: value.campus,
        registrationMethod: from_candid_RegistrationMethod_n24(_uploadFile, _downloadFile, value.registrationMethod),
        whatsappPhone: value.whatsappPhone
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_ItemView>;
}): {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<ItemView>;
} {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: from_candid_vec_n9(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    sold: null;
}): ItemStatus {
    return "active" in value ? ItemStatus.active : "sold" in value ? ItemStatus.sold : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HouseItems: null;
} | {
    Clothes: null;
} | {
    Books: null;
} | {
    Electronics: null;
} | {
    BedsAndMattresses: null;
}): Category {
    return "HouseItems" in value ? Category.HouseItems : "Clothes" in value ? Category.Clothes : "Books" in value ? Category.Books : "Electronics" in value ? Category.Electronics : "BedsAndMattresses" in value ? Category.BedsAndMattresses : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ItemView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ItemView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ItemView_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): Variant_ok_notFound_unauthorized {
    return "ok" in value ? Variant_ok_notFound_unauthorized.ok : "notFound" in value ? Variant_ok_notFound_unauthorized.notFound : "unauthorized" in value ? Variant_ok_notFound_unauthorized.unauthorized : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    email: string;
} | {
    phone: string;
}): {
    __kind__: "email";
    email: string;
} | {
    __kind__: "phone";
    phone: string;
} {
    return "email" in value ? {
        __kind__: "email",
        email: value.email
    } : "phone" in value ? {
        __kind__: "phone",
        phone: value.phone
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ProfileView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ProfileView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ProfileView_n22(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ItemView>): Array<ItemView> {
    return value.map((x)=>from_candid_ItemView_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BrowseFilter_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BrowseFilter): _BrowseFilter {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CreateItemInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateItemInput): _CreateItemInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterInput_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterInput): _RegisterInput {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_RegistrationMethod_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationMethod): _RegistrationMethod {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): _SortOrder {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateItemInput_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateItemInput): _UpdateItemInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    imageRefs: Array<string>;
    description: string;
    category: Category;
    priceKES: bigint;
}): {
    title: string;
    imageRefs: Array<string>;
    description: string;
    category: _Category;
    priceKES: bigint;
} {
    return {
        title: value.title,
        imageRefs: value.imageRefs,
        description: value.description,
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        priceKES: value.priceKES
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minPriceKES?: bigint;
    sortOrder: SortOrder;
    maxPriceKES?: bigint;
    category?: Category;
    keyword?: string;
}): {
    minPriceKES: [] | [bigint];
    sortOrder: _SortOrder;
    maxPriceKES: [] | [bigint];
    category: [] | [_Category];
    keyword: [] | [string];
} {
    return {
        minPriceKES: value.minPriceKES ? candid_some(value.minPriceKES) : candid_none(),
        sortOrder: to_candid_SortOrder_n3(_uploadFile, _downloadFile, value.sortOrder),
        maxPriceKES: value.maxPriceKES ? candid_some(value.maxPriceKES) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n5(_uploadFile, _downloadFile, value.category)) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none()
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    campus: Campus;
    registrationMethod: RegistrationMethod;
    whatsappPhone: string;
}): {
    name: string;
    campus: _Campus;
    registrationMethod: _RegistrationMethod;
    whatsappPhone: string;
} {
    return {
        name: value.name,
        campus: value.campus,
        registrationMethod: to_candid_RegistrationMethod_n28(_uploadFile, _downloadFile, value.registrationMethod),
        whatsappPhone: value.whatsappPhone
    };
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "email";
    email: string;
} | {
    __kind__: "phone";
    phone: string;
}): {
    email: string;
} | {
    phone: string;
} {
    return value.__kind__ === "email" ? {
        email: value.email
    } : value.__kind__ === "phone" ? {
        phone: value.phone
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): {
    newest: null;
} | {
    priceDesc: null;
} | {
    priceAsc: null;
} {
    return value == SortOrder.newest ? {
        newest: null
    } : value == SortOrder.priceDesc ? {
        priceDesc: null
    } : value == SortOrder.priceAsc ? {
        priceAsc: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    HouseItems: null;
} | {
    Clothes: null;
} | {
    Books: null;
} | {
    Electronics: null;
} | {
    BedsAndMattresses: null;
} {
    return value == Category.HouseItems ? {
        HouseItems: null
    } : value == Category.Clothes ? {
        Clothes: null
    } : value == Category.Books ? {
        Books: null
    } : value == Category.Electronics ? {
        Electronics: null
    } : value == Category.BedsAndMattresses ? {
        BedsAndMattresses: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
